-- 코드를 입력하세요
SELECT
    B.AUTHOR_ID
    , A.AUTHOR_NAME
    , B.CATEGORY
    , SUM(S.SALES * B.PRICE) AS TOTAL_SALES  -- 매출액: 판매량 * 판매가
FROM
    BOOK AS B
    JOIN AUTHOR AS A
        ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES AS S
        ON B.BOOK_ID = S.BOOK_ID
WHERE
    S.SALES_DATE LIKE '2022-01%'  -- 2022년 1월의 도서 판매 데이터만 조회
GROUP BY
    B.AUTHOR_ID
    , B.CATEGORY
ORDER BY
    B.AUTHOR_ID
    , B.CATEGORY DESC;