-- 코드를 입력하세요
SELECT
    U.USER_ID
    , U.NICKNAME
    , CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS ADDRESS
    , CONCAT(LEFT(U.TLNO, 3), '-', 
           MID(U.TLNO, 4, 4), '-', 
           RIGHT(U.TLNO, 4)) AS PHONE
FROM
    USED_GOODS_USER AS U
JOIN
    USED_GOODS_BOARD AS B ON U.USER_ID = B.WRITER_ID
GROUP BY
    U.USER_ID
HAVING
    COUNT(*) >= 3
ORDER BY
    U.USER_ID DESC;