-- 코드를 입력하세요
SELECT 
    O.ANIMAL_ID, 
    O.NAME
FROM 
    ANIMAL_OUTS AS O
LEFT JOIN 
    ANIMAL_INS AS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE 
    I.ANIMAL_ID IS NULL  -- 보호소에 들어온 기록이 없는 동물 필터링
ORDER BY 
    O.ANIMAL_ID;