-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM
    USED_GOODS_BOARD AS B
JOIN
    USED_GOODS_FILE AS F
    ON B.BOARD_ID = F.BOARD_ID
WHERE
    B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)  -- 조회수가 가장 높은 중고거래 게시물 필터링
ORDER BY
    F.FILE_ID DESC;  -- 파일 ID를 기준으로 내림차순 정렬