-- 코드를 입력하세요
SELECT
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK AS B
JOIN
    BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
WHERE
    S.SALES_DATE LIKE '2022-01%'  -- 2022년 1월의 판매 기록만 필터링
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY;