-- 코드를 작성해주세요
SELECT
    COUNT(*) AS FISH_COUNT
    , MAX(LENGTH) AS MAX_LENGTH
    , FISH_TYPE
FROM
    FISH_INFO
GROUP BY
    FISH_TYPE
HAVING
    AVG(IFNULL(LENGTH, 10)) >= 33  -- 10cm 이하의 물고기들은 10cm로 취급하여 평균 길이 계산
ORDER BY
    FISH_TYPE;